name: Run tests

on: [push, pull_request]

jobs:
  run_tests:
    strategy:
      matrix:
        nvim_tag: [v0.5.0, v0.5.1, v0.6.0, v0.6.1]

    name: Run tests
    runs-on: ubuntu-20.04
    env:
      NVIM_TAG: ${{ matrix.nvim_tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh

      - name: Run tests
        run: |
          bash ./run_tests.sh
